services:
  selenium-tests:
    image: selenium-tests
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/home/seluser/.m2
    command:
      - sh
      - -c
      - |
        cd /app
        mvn clean test -DsuiteXmlFile=./src/test/resources/Alpha_Regression.xml

#git clone https://github.com/LiyWu/HWSeleniumframework.git
#cd HWSeleniumframework
